# Site settings
title: CPC Group
email: carolin.mueller@ext.uni.lu
url: https://compphotochem.github.io/
description: "Group Website"
        
keywords: "– Computational Photochemistry and -physics – (Kinetic) Modeling of Multivariate Spectra – Chemoinformatics –" 
meta_author: Carolin Müller

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 7E5273 # '126,82,115'
  primary-rgb: 126,82,115 
  secondary: 3C1028 # '60,16,40'
  secondary-dark: 2C001E # '44,0,30'

# Footer settings
footer:
  copyright: Dr. Carolin Müller
  location: About
  social: Meet Us
  credits: Contribute

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/carolin-m%C3%BCller-b2581723b
  - title: github
    url: https://github.com/CompPhotoChem/CompPhotoChem.github.io
  - title: instagram
    url: https://www.instagram.com/caro_chemie/

# Postal address (add as many lines as necessary)
address:
  - line: <a href="https://compphotochem.github.io/" style="color:white">Home</a>
  - line: <a href="https://compphotochem.github.io/impressum/" style="color:white">Impressum</a>
  - line: 'Powered by Jekyll.'

# Credits content
credits: '<a href="https://compphotochem.github.io/positions/" class="btn btn-lg btn-outline">Join the Group &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</a><br> <a href="https://compphotochem.github.io/contact/" class="btn btn-lg btn-outline">Contact the Group </a>'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""      
