# Site settings
title: CompPhotoChem Group
email: carolin.mueller@ext.uni.lu
url: https://compphotochem.github.io/
description: "Group Website"
        
keywords: "– Computational Photochemistry and -physics – (Kinetic) Modeling of Multivariate Spectra – Chemoinformatics –" 
meta_author: Carolin Müller

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 7E5273 # '126,82,115'
  primary-rgb: 126,82,115 
  secondary: 3C1028 # '60,16,40'
  secondary-dark: 2C001E # '44,0,30'

# Footer settings
footer:
  copyright: Dr. Carolin Müller
  location: Contact
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/carolin-m%C3%BCller-b2581723b
  - title: github
    url: https://github.com/CompPhotoChem/CompPhotoChem.github.io

# Postal address (add as many lines as necessary)
address:
  - line: Address Line 1
  - line: Address Line 2

# Credits content
credits: 'Powered by Jekyll.<br> <a href="/impressum/" class="btn btn-lg btn-outline">Impressum</a>' # add impressum as link

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
